server:
  #port: 8000
  port: ${PORT:8000} #
spring:
  kafka:
    #producer:
    #  bootstrap-servers: localhost:29092 #porta onde esta rodando o servico do Kafka
    bootstrap-servers: ${KAFKA_HOST:localhost:29092} #variavel KAFKA_HOST definida no docker compose caso não exista ele vali usar localhost:29092