server:
  #port: 8200
  port: ${PORT:8200} #
spring:
  kafka:
    #producer:
    #  bootstrap-servers: localhost:29092 #porta onde esta rodando o servico do Kafka
    bootstrap-servers: ${KAFKA_HOST:localhost:29092} #variavel KAFKA_HOST definida no docker compose caso nao exista ele vali usar localhost:29092
